## Runner settings
CREATE_SUBDIR_PER_RUN: True  # create a subdirectory for each run
server_file: './server.py'  # server file
client_file: './client.py'  # client file

## File settings
config: './config.yaml'  # use config file, will overwrite any other arguments
data_dir: '../../../datasets/flamingo_generated/'  # dataset directory
work_dir: './runs/mnist/'  # working directory

## Training settings
seed: 2024  # random seed
batch_size: 64  # batch size
test_batch_size: 64  # test batch size
lr: 0.001  # learning rate
weight_decay: 0.0001  # weight decay
max_epochs: 100  # epoch
dropout: 0.5  # dropout rate
momentum: 0.9  # momentum
local_epochs: 1  # local epochs

## Federated learning settings
num_clients: 15  # number of clients
num_training_clients: 5  # number of training clients

# custom settings
method: fedavg  # For distiguish federated learning method
# mnist:cnn, mlr, dnn; cifar10: mlr, cnn, dnn
model_type: cnn  # model type
dataset_type: mnist  # dataset_type

# Logging settings
log_path:      # log directory, set blank to use default
verb: 1  # verbose, True or False


